config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:index, :new, :create, :show] do
        resources :comments, only: [:index, :new]
    end
  end

  resources :comments, only: [:create, :show]

  resources :posts, except: [:index, :new, :create, :show]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :text             not null
#  user_id           :integer          not null
#  post_id           :integer          not null
#  parent_comment_id :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Comment < ActiveRecord::Base
  validates :content, :user_id, :post_id, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  belongs_to :post

  belongs_to :parent_comment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :user_id, presence: true

  belongs_to :user

  has_many :post_subs
  has_many :subs,
    through: :post_subs

  has_many :comments
end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  sub_id     :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ActiveRecord::Base
  validates :sub, :post, presence: true

  belongs_to :sub, inverse_of: :post_subs
  belongs_to :post, inverse_of: :post_subs
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :user_id,  presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :posts,
    through: :post_subs

  has_many :post_subs
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :session_token, presence: true, uniqueness: true
  validates :password, presence: true, allow_nil: true
  validates :password_digest, presence: true
  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
     user = User.find_by(username: username)
     return nil if user.nil?
     user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :login_user!

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @sub = Sub.find(params[:sub_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to sub_post_url(params[:sub_id], params[:post_id])
    else
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/post_subs_controller.rb
class PostSubsController < ApplicationController

end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_author, only: [:edit, :update]

  def new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to sub_url(Sub.find(@post.sub_ids[0]))
    else
      render :new
    end
  end

  def index
    @sub = Sub.find(params[:sub_id])
    @posts = @subs.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    redirect_to sub_url(@post.sub)
  end

  def destroy

  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :user_id, sub_ids: [])
  end

  def ensure_author
    @post = Post.find(params[:id])
    if current_user.id != @post.user_id
      redirect_to sub_url(@post.subs.first)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if user.nil?
      render :new
    else
      login_user!(user)
      redirect_to subs_url
    end
  end

  def destroy
    user = current_user
    user.reset_session_token!
    session[:session_token] = nil

    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_moderator, except: [:show, :index, :new, :create]

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def new
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    @sub.update(sub_params)
    redirect_to sub_url(@sub)
  end

  def index
    @subs = Sub.all
  end

  def destroy

  end

  private
  def ensure_moderator
    @sub = Sub.find(params[:id])

    if current_user.id != @sub.user_id
      redirect_to sub_url(@sub)
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      render json: @user
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to new_user_url
  end

  def edit
  end

  def update
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = "<input "
    html += "type=\"hidden\" "
    html += "name=\"authenticity_token\" "
    html += "value=\"<%= h(form_authenticity_token) %>\">"

    html.html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_subs_helper.rb
module PostSubsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<form action="<%= comments_url %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="post_id" value="<%= @post.id %>">
  <input type="hidden" name="sub_id" value="<%= @sub.id %>">

  Commenting on Post: <%= @post.title %><br>
  Content:
  <textarea name="comment[content]" rows="8" cols="40"></textarea>
  <input type="submit" value="Submit Comment">
</form>

app/views/comments/show.html.erb
<%= @comment.content %>
<br>
<input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
<%= link_to "Create Comment", new_comment_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <%= "Welcome #{current_user.username}!" %>
    <%= button_to "Log out", session_url, method: :delete %>
    <br>
  <% elsif request.url != new_session_url %>
    <%= button_to "Log in", new_session_url, method: :get %>
    <br>
  <% end %>
<%= yield %>

  <footer>
      <%= link_to "Subs Index", subs_url %>
  </footer>
</body>
</html>

app/views/posts/edit.html.erb
<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  Title<input type="text" name="post[title]" value="<%= @post.title %>">
  <br>
  Content <textarea name="post[content]" rows="8" cols="40"><%= @post.content %></textarea>
  <br>
  Subs:
  <br>
  <% Sub.all.each do |sub| %>
    <%= sub.title %><input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    <br>
  <% end %>
  <input type="submit" value="Submit">
</form>

app/views/posts/index.html.erb
<ol>
  <% @posts.each do |post| %>
      <li>
        Title: <%= link_to "#{post.title}", sub_post_url(@sub.id, post) %>
        <br>
        Posted by: <%= post.user.username %>
        <% if current_user.id == post.user.id %>
          <%= button_to "Edit Post", edit_post_url(post), method: :get%>
        <% end %>
      </li>
        <br>
  <% end %>
</ol>

app/views/posts/new.html.erb
<form action="<%= sub_posts_url %>" method="post">
  <%= auth_token %>
  Title<input type="text" name="post[title]">
  <br>
  Content <textarea name="post[content]" rows="8" cols="40"></textarea>
  <br>
  Subs:
  <br>
  <% Sub.all.each do |sub| %>
    <%= sub.title %><input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>">
    <br>
  <% end %>
  <input type="submit" value="Submit">
</form>

app/views/posts/show.html.erb
Title: <%= @post.title %>
<br>
Content: <%= @post.content %>
<br>
<br>
Comments:
<ol>
  <% @post.comments.each do |comment| %>
    <li>
      <%= comment.content %>
      <br>
      <%= link_to "Comment On This Comment", comment_url(comment) %>
    </li>
    <br>
  <% end %>
</ol>

<%= button_to "Create Comment On Post", { controller: "comments", action: "new", sub_id: params[:sub_id], post_id: params[:id] }, method: :get %>

app/views/sub/new.html.erb
<form action="<%= subs_url %>" method="post">
  <%= auth_token  %>
  Create New Sub!
  <br>
  Title: <input type="text" name="sub[title]">
  Description: <textarea name="sub[description]"></textarea>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/subs/edit.html.erb
<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token  %>
  Edit <%= @sub.title %>
  <br>
  Title: <input type="text" name="sub[title]", value = "<%= @sub.title %>">
  Description: <textarea name="sub[description]"> <%= @sub.description %></textarea>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/subs/index.html.erb
<% @subs.each do |sub| %>
  <%= link_to "#{sub.title}", sub_url(sub) %>
<% end %>

app/views/subs/new.html.erb
<form action="<%= subs_url %>" method="post">
  <%= auth_token  %>
  Create New Sub!
  <br>
  Title: <input type="text" name="sub[title]">
  Description: <textarea name="sub[description]"></textarea>
  <br>
  <input type="submit" value="Submit">
</form>

app/views/subs/show.html.erb
Welcome to <%= @sub.title %>'s page!
<br>
This sub is all about: <%= @sub.description %>
<br>
Moderator: <%= @sub.moderator.username %>
<br>
<br>
Posts:
  <%= render template: 'posts/index' %>
<% if logged_in? %>
  <%= link_to "Make a Post", new_sub_post_url(@sub) %>
<% end %>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  Username: <input type="text" name="user[username]">
  Password: <input type="text" name="user[password]">
  <input type="submit" value="Submit">
</form>